### ISSUE TITLE
plugin doesnt work "Edit with elementor" button

### ISSUE THREAD

**Issue by Gallitoo** [Nikschavan/header-footer-elementor#277] opened 2020-04-06 12:48 UTC
Hi. Ive downloaded the plugin header footer elementor because I was creating a footer template in Elementor without this plugin but when I publish it, it didnt appear anywhere, so I though I had to download the plugin.
But Ive already dowloaded the plugin and when I create a new one ... as the instructions says.. (appearance->header footer elementor->add new one..) I write the options, name, displays on... all web and after that I click on "Edit with elementor" and nothing ocurs... Ive tried also to publish it before click the button but all the same.. It doesnt open the elementor windows to creat...

**Comment by SuryawanshiPrajakta** [comment] 2020-04-07 07:03
Hello @Gallitoo,

Thank you for getting in touch with us!

This should not happen. Could you please confirm once if the issue is due to the Elementor - Header, Footer, and Blocks by using [Health Check](https://wordpress.org/plugins/health-check/) plugin?

If yes, then please open a support ticket from [here](https://www.brainstormforce.com/open-a-ticket/). We will be more than happy to help you in resolving this.

Regards,
Prajakta Suryawanshi

**Comment by Gallitoo** [comment] 2020-04-09 18:54
Ive already installed it... but what do I have to do with the plugin? do I have to tell you about the php version of the plugin in tools.. or activating the diagnostic mode, or what? I am new working with websites... Thanks

**Comment by SuryawanshiPrajakta** [comment] 2020-04-10 15:10
Hello @Gallitoo,

No worries! Please open a support ticket from [here](https://www.brainstormforce.com/open-a-ticket/).

One of our technical support team members will assist you in resolving this by taking a closer look.

Looking forward to resolving your issue ASAP.

Regards,
Prajakta Suryawanshi

**Comment by SuryawanshiPrajakta** [comment] 2020-04-29 13:00
Hello @Gallitoo,

We haven't heart back from you regarding this issue. Could you please let us know if you are still facing this issue so that we can help you in resolving it?

Looking forward to hearing from you.

Regards,
Prajakta Suryawanshi

**Closed by SuryawanshiPrajakta** 2020-04-29 13:00 UTC
