### ISSUE TITLE
header-footer-elementor not supported in elementor hello theme

### ISSUE THREAD

**Issue by jhchandler** [Nikschavan/header-footer-elementor#157] opened 2019-04-21 05:06 UTC
Elementor-Hello Theme is an Elementor Theme, one would think that Elementor plugins would work with Elementor Themes.  In this case, that is not true.  I get a warning that Header Footer Elementor plugin is not supported on my current Theme, which is the Elementor Hello Theme.

Sounds like a circular joke, but it is frustrating, especially since I use this combination on one server, and it works fine in my main domain, but when I add the theme and plugin in a sub-domain or on a website on a different server, I get the warning about incompatibility.  Stranger still, the graphic for the theme on the sub-doman and the other server look the same, but are different on the original host domain, even though I both copied it from the Elementor website, then deleted the theme and then used a copied version from my original website.  In both cases the Theme graphic was the same, and the incompatibility notification was the same.

**Comment by Nikschavan** [comment] 2019-06-17 12:25
Thank you for your interest @jhchandler I will be tackling this in the next update of the plugin.

For now, I am closing this as a duplicate of an already existing issue - #118 118

**Closed by Nikschavan** 2019-06-17 12:25 UTC

**Comment by Nikschavan** [comment] 2019-12-09 09:43
This will be fixed with v1.2.0 (#207)

@jhchandler  Can you try v1.2.0 which adds support for all the themes - https://share.getcloudapp.com/WnuEdN7m

Your feedback will be very helpful.

**Comment by Shalice1218** [comment] 2022-08-23 08:55
True; I tried the hello theme from a YouTube suggestion, though I used Ocean WP and Astra more. His logic is Hello theme will never have compatibility issues because it officially belongs to Elementor. The truth is frustrating, it displays all good from my computer, but when I asked my team to try from China from a different explorer, the menu didn't look right. Also, it displays all good when I tried the menu with the mobile response, but it seems totally different even with Google Search Engine. 
![2065d25c80ad657766324cff5995daf](https://user-images.githubusercontent.com/97784272/186115481-c7524511-617f-401c-9d52-0cfe73545f73.jpg)

<img width="946" alt="600c3c8da9b607eeb708789f750e621" src="https://user-images.githubusercontent.com/97784272/186115616-3f84959f-ea5b-4d3f-86d5-c490d0cceec1.png">

![1661244831345](https://user-images.githubusercontent.com/97784272/186116337-440d9968-4aa8-4fdd-89c7-4a948f812368.png)

![ebbafd98824ca80c4a68bf50629cd60](https://user-images.githubusercontent.com/97784272/186116379-62d7111f-ca34-43c6-bad8-4ac8c99c2af9.jpg)
