### ISSUE TITLE
Different header for other pages

### ISSUE THREAD

**Issue by tivako** [Nikschavan/header-footer-elementor#94] opened 2018-03-15 08:17 UTC
I would like to have one header for the mainpage and one header for all other pages. Is this possible.?Cannot find it.

**Comment by Nikschavan** [comment] 2018-05-22 05:49
Right now this is available from Astra Pro's Custom Layouts addon - https://wpastra.com/docs/custom-header/

Duplicate of #29

**Closed by Nikschavan** 2018-05-22 05:49 UTC
