### ISSUE TITLE
Critical Error Message

### ISSUE THREAD

**Issue by goakes2** [Nikschavan/header-footer-elementor#273] opened 2020-04-03 14:36 UTC
Hello. Since I updated Wordpress to V5.4, go into the Header Footer Builder and select Header to edit in Elementor, I get the following error message "There has been a critical error on your website. Please check your site admin email inbox for instructions. Learn more about debugging in WordPress." When I deactivate the plugin and reactivate, I can then edit again apart from losing elements that have been applied through the plugin. I don't know if the plugin is now clashing with another or this plugin needs updating. Assistance would be appreciated.

**Comment by SuryawanshiPrajakta** [comment] 2020-04-03 15:24
Hey @goakes2,

Thank you for reaching us out. This should not happen.

As we checked on our end, Elementor - Header, Footer, and Blocks is working as expected with WordPress v5.4.

Please reach out to us from [here](http://uaelementor.com/support/), so that we can debug the issue closely.

Regards,
Prajakta Suryawanshi

**Comment by goakes2** [comment] 2020-04-03 15:53
Hello. I hit the link and it takes me to a Needs Support page. The search does not bring up any results. I then go to the Submit Ticket page and I am not clear where to go from here as my question is not a pre-sales or and I do not have pro support?

**Comment by SuryawanshiPrajakta** [comment] 2020-04-06 10:37
Hello @goakes2 ,

We had an issue with the Menu Cart widget. There was an error when cart is empty. We have fixed this issue with EHF v1.4.1. 

Please update EHF to v1.4.1 and check if Edit with Elementor works for you. Else, we will recommend you to use [Health Check](https://wordpress.org/plugins/health-check/) plugin and confirm if the issue is due to the Elementor - Header, Footer and Blocks.

If yes, then you can open a support ticket from [here](https://uaelementor.com/contact/?psq=general-or-pre-sale-questions) if you do not have any of our paid product.

Looking forward to hearing from you.

Regards,
Prajakta Suryawanshi

**Comment by SuryawanshiPrajakta** [comment] 2020-04-29 12:55
Hello @goakes2,

We did not hear back from you on this issue. I hope it is resolved now.

We are closing this issue as of now. Please do not hesitate to contact us in case of future queries.

Regards,
Prajakta Suryawanshi

**Closed by SuryawanshiPrajakta** 2020-04-29 12:55 UTC
