### ISSUE TITLE
Text of page section item in NavMenu has still "hover" color

### ISSUE THREAD

**Issue by Ingrown29** [Nikschavan/header-footer-elementor#281] opened 2020-04-17 13:07 UTC
Hi I created an header with your awesome header-footer-plugin for elementor but I have problem with text color in NavView. On one of the pages I have two sections which are added to the NavView as menu items but when I have this page opened, both of them has color that I choosed only for hover action. In the menu I have also one more item which references to another page but this has normal behaviour. The link hover effect with its color under this two sections in NavView has also normal behaviour. Can you please help me solve this issue? Thank you.

I am usin Hello Elementor theme with Wordpress 5.3.2

**Comment by SuryawanshiPrajakta** [comment] 2020-04-20 04:13
Hello @Ingrown29,

Thank you for getting back to us!

Could you please provide us with a few steps to reproduce this issue?

This will help us in checking your issue at our end so that we can provide you with a solution to this.

Looking forward to hearing from you.

Regards,
Prajakta Suryawanshi

**Comment by Ingrown29** [comment] 2020-04-20 12:00
Hi  @SuryawanshiPrajakta,

Thank you fro your reply.

Fortunately, I got that solved after implementing plugin "scroll page to id", but I found another bug.

The header-footer-plugin is displaying header in elementor maintenance mode even when I restricted header-footer-plugin to not show the header in my custom maintenance template. Do you know how to solve that?

And I have also one more question. Is it possible to display NavMenu item underline only on hover? And disable it when the item is active or non-active?

Thank you

**Comment by SuryawanshiPrajakta** [comment] 2020-04-21 14:23
Hello @Ingrown29,

Thank you for sharing the site URL!

I had a look at your issue. I can see that the 'current-menu-item' class is getting added to each menu item which should not be happening and this is working fine at our end. We will need to have a closer look at your website's backend to check this.

About the maintenance mode issue - You can set 'User Role' to 'Logged In' so that the header will not be visible in the maintenance mode. Resume it to all users once your site will be live. 

About the Nav Menu item underline only on hover - This is possible with some custom CSS.
Please use the below CSS -

`.elementor-2138 .elementor-element.elementor-element-2cc16ef .hfe-nav-menu-layout:not(.hfe-pointer__framed) .menu-item.parent a.hfe-menu-item:hover:after{
	background-color: #1E9CF7;
}

.elementor-2138 .elementor-element.elementor-element-2cc16ef .hfe-nav-menu-layout:not(.hfe-pointer__framed) .menu-item.parent a.hfe-menu-item:after{
	background-color: #fff;
}`

Please open support here from [here](https://www.brainstormforce.com/open-a-ticket/) so that we can debug the first concern closely.

Looking forward to hearing from you.

Regards,
Prajakta Suryawanshi

**Comment by Ingrown29** [comment] 2020-04-21 23:03
Hi @SuryawanshiPrajakta,

Thank you for your reply.

That CSS code for underline only on hover works great!

I have also checked the maintenance mode and I had already set 'User Role' to 'Logged In'. I know that when I am logged in as administrator I can see whole website without any restriction but I opened the website on chrome's incognito mode where I WASN'T logged in and I saw the header and footer alongside the maintenance mode enabled. It happened also when I opened the website on different computer. So this didn't solve my problem. Any other solutions?

Thank you

**Comment by SuryawanshiPrajakta** [comment] 2020-04-22 08:32
Hello @Ingrown29,

Thank you for getting back to us!

Unfortunately, I was unable to reproduce the issue with the maintenance issue on my end. I cannot see the EHF header if I am logged out.

However, I can see that you have opened a ticket. One of our support team members will help you resolve the issues from thereby checking the scenario on your site.

Regarding closing the dropdown when one of the items is clicked, as of now, regretfully, this is not possible through the widget.
 
Let us know how can we help you further.

Regards,
Prajakta Suryawanshi

**Comment by Ingrown29** [comment] 2020-04-24 18:08
Hi @SuryawanshiPrajakta,

Thank you for your reply.

You helped me as much as you could. I don't have more questions yet. If yes, I will let you know or I will ask one of your support team members once they response on my ticket.

Thank you again.

**Comment by SuryawanshiPrajakta** [comment] 2020-04-29 12:49
Hey @Ingrown29,

I am glad that I could help!

Please do not hesitate to contact us for future queries.

Regards,
Prajakta Suryawanshi

**Closed** 2020-04-29 12:49 UTC
Labels: question
